version: '3'
services:
  api:
    build:
      context: api
      dockerfile: ./Dockerfile
    ports:
      - 8088:8088

  front:
    build:
      context: front
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
