version: '3'
services:
  api:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8088:8088

  front:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
